# Generated by Django 2.1.4 on 2018-12-06 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('descuento', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=100)),
                ('desc_producto', models.CharField(max_length=200)),
                ('tipo_producto', models.CharField(max_length=3)),
                ('precio_producto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tienda', models.CharField(max_length=30)),
                ('dir_tienda', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('jefe_tienda', models.CharField(max_length=80)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_vendedor', models.CharField(max_length=100)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('comentario', models.CharField(blank=True, max_length=100)),
                ('valor_pesos', models.FloatField(blank=True, default=0)),
                ('total_pesos', models.FloatField(blank=True, default=0)),
                ('descuento', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Oferta')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tienda')),
                ('vendedor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='id_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Producto'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Regione'),
        ),
    ]
